include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - coverage/**
    - .idea/**
    - .vscode/**
    - docs/**
    - windows/flutter/ephemeral/**
    - android/.gradle/**
    - ios/Pods/**
    - linux/flutter/ephemeral/**
    - macos/Flutter/ephemeral/**
  errors:
    todo: ignore

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
