// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyXdDGZNUN6cqGnhvr4EWB18HdVLB-roQ',
    appId: '1:420957221495:web:9a54a28c210d52e23a0c72',
    messagingSenderId: '420957221495',
    projectId: 'mental-smile-platform',
    authDomain: 'mental-smile-platform.firebaseapp.com',
    storageBucket: 'mental-smile-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBRNmoAVqHTctD-eMuznSrxojwt3ewiMg',
    appId: '1:420957221495:android:356d24a12835b9723a0c72',
    messagingSenderId: '420957221495',
    projectId: 'mental-smile-platform',
    storageBucket: 'mental-smile-platform.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMcsJptGGi_8q74YPmS4g5-A7MZ8IYFv8',
    appId: '1:643226562725:web:fe79ac56c44f928144dd4c',
    messagingSenderId: '643226562725',
    projectId: 'mental-smile-platform',
    authDomain: 'mental-smile-platform.firebaseapp.com',
    storageBucket: 'mental-smile-platform.firebasestorage.app',
    measurementId: 'G-FCTE266FRR',
  );
}
