name: mental_smile_library_capsule_example
description: Mental Smile Library Capsule harness
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  mental_smile_library_capsule:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
